###########################################################################
### Server 설정
###########################################################################
server:
  servlet:
    context-path: /${spring.application.root}

###########################################################################
### Spring 설정
###########################################################################
spring:
  application:
    root: template
    name: api-template

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(s7xb0CW4sVRlgT7tViYRjOnYVVRU8sh2gKhRiD5ex95iXkI8GZ9u+qf7g2y9sOmxDzmqoj8HZey0t4IU6Qa+WoORGIZs6jGq+nKMwySOk02x41qdVRZUaOsc85TwYUl9)
    username: ENC(TeMlqkLccRHGQ4PzBB1oUPUqDvK4ZZkeaXOewXdLGJ5usGhqDfk/eerpH4dRRdCT)
    password: ENC(xpgoun0Urk0dmen22yNCktet0Ha6mfIdb6ZENT0Km51PvW96YE32O7GDPiq4uDHF)

###########################################################################
### log config 위치 설정
###########################################################################
logging:
  config: classpath:logback/spring-logback.xml

###########################################################################
### mybatis 설정
###########################################################################
mybatis:
  type-aliases-package: org.template.template.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mappers/**/*Mapper.xml

###########################################################################
### Swagger 설정
###########################################################################
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: list

  cache:
    disabled: true

  override-with-generic-response: false
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

###########################################################################
### jasypt 설정
###########################################################################
jasypt:
  encryptor:
    password: ${ENCRYPTOR_PROFILE}
