###########################################################################
### Server 설정
###########################################################################
server:
  servlet:
    context-path: /${spring.application.root}

###########################################################################
### Spring 설정
###########################################################################
spring:
  application:
    root: template
    name: api-template

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(lV5aDNnMkqvh2oVHoutvvhhY9j/1LquDEpuscBetxUC3aLQU3a+6fiIBmXcYlZbYNScbI1l1fVZhPGOZDfrkGqrRwSuaeZ8D38qLxfcbc0ffX77BP/KKxdf5UEBReMBc)
    username: ENC(qj0bdp5i0aFsAD+bjtkVcHieCKKtG6qCJF8OW4KDUdKZOaZ6yLz0i0fbMsuQIG3m)
    password: ENC(SUOFjAAQv9EQFgiOvY0GrZAMIwNc4TutJTiZQA1L2gZvLvVNz4sF7f0i6/1TSj3A)
#    url: jdbc:log4jdbc:postgresql://ip_address/db_name
#    username: username
#    password: password

###########################################################################
### log config 위치 설정
###########################################################################
logging:
  config: classpath:logback/spring-logback.xml

###########################################################################
### mybatis 설정
###########################################################################
mybatis:
  type-aliases-package: org.template.template.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mappers/**/*Mapper.xml

###########################################################################
### Swagger 설정
###########################################################################
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: list

  cache:
    disabled: true

  override-with-generic-response: false
  model-and-view-allowed: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

###########################################################################
### jasypt 설정
###########################################################################
jasypt:
  encryptor:
    password: ${ENCRYPTOR_PROFILE}
